version: '3.9'

services:
  webapi:
    build:
      context: ./web-api
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    volumes:
      - ./web-api:/var/www/app

  webapp:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - '3001:80'
    depends_on:
      - webapi
