name: "Build and Deploy"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # On aurais pu utiliser une strategy pour testé différentes version de NodeJS

    steps:
      # Vérification du contenu du commit.
      - uses: actions/checkout@v3

      # Mise en place de l'environnement NodeJS.
      - name: Setup NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # Installation des dépendences.
      - name: Install dependencies
        run: npm ci

      # Installation de Nx avec la même version que celle utilisé lors du développement.
      - name: Install nx
        run: npm install nx@15.7.2

      # Lancement des test sur notre applications Front
      - name: Test Web-App Application
        run: nx run-many --targets=test --all --no-cache

      # Construction de nos application avec Nx (Monorepo)
      - name: Build Web-App Application
        run: nx run-many --targets=build --prod --no-cache
